### ISSUE TITLE
Product category enable/disable does not reflects on immediate get products API

### ISSUE THREAD

**Issue by avyukta** [rvcssingh/BrewBuck#23]
1. Go to Product category
2. Activate/Deactivate category

Expected:
Products against category should return list of Activate/Deactivate products

Actual:
Changes does not reflects

**Comment by rvcssingh** [comment]
i have fixed the issue.Please verify and close it asap.

**Comment by rvcssingh** [comment]
also let me know what are the events which needs sync behaviour

**Comment by vikas2402** [comment]
Verified
