### ISSUE TITLE
Bill Order edit | Bad request

### ISSUE THREAD

**Issue by avyukta** [rvcssingh/BrewBuck#30]
1. Create Bill
2. Edit
3. Update Address
4. Error > "Bad Request"

**note: Request payload seems legit, please assign back to me if UI issue.
{
  "id": "bill-d934c1bf-aa28-43a2-ae74-beb8ac1bf9a9",
  "billNumber": "BILL-00000001",
  "billDate": "2017-09-09",
  "company": {
    "name": "winterfall",
    "email": "ravikant.singh1804@gmail.com",
    "gstin": "22CJRPS3351Q1Z5",
    "phone": "8983729928"
  },
  "companyAddress": {
    "addressLine": "Baner",
    "city": "Pune",
    "state": "Daman and Diu",
    "postalCode": "124555",
    "country": "India",
    "phoneNumber": "8983729928"
  },
  "vendorName": "Vendor Name",
  "vendorGSTIN": "27CJRPS3351Q1Z5",
  "billingAddress": {
    "addressLine": "Bhel chowk",
    "city": "pune",
    "state": "Maharashtra",
    "postalCode": "231520",
    "country": "India"
  },
  "lineItems": [
    {
      "lineItemId": "billdetail-3ade8603-7968-4f56-b006-6e83c20812fa",
      "productName": "Apple",
      "id": "product-7b235d98-6668-4562-baa5-53a9502b242c",
      "productType": 0,
      "productCode": "1234",
      "uom": "BAG - Bag",
      "quantity": 450,
      "rate": 1500,
      "discount": 0,
      "taxable": 675000,
      "cgstSlab": 0,
      "cgstAmount": 0,
      "sgstSlab": 0,
      "sgstAmount": 0,
      "igstSlab": 3,
      "igstAmount": 20250,
      "productTotal": 695250
    }
  ],
  "totalSGST": 0,
  "totalCGST": 0,
  "totalIGST": 20250,
  "totalAmount": 695250
}

**Comment by rvcssingh** [comment]
verified and removed validation check for
 //|| request.Data.BillSeries < 1)
why this is required
