### ISSUE TITLE
RoleModule : Update Role: Isenable is false and role name is null

### ISSUE THREAD

**Issue by rvcssingh** [rvcssingh/BrewBuck#6]
api call : POST http://localhost:5757/api/Role/UpdateRolePermission
payload : {"id":"role-9a28215e-d966-424e-9d88-0ad55c83a76b","roleName":null,"isEnable":false,"modulePermissions":[{"module":"Product Category","permissions":[{"permissionId":"09df4136-5754-4ab1-9e5f-c64c6e077d53","apiCode":"Update","hasPermission":true,"action":"productcategory2"},{"permissionId":"20778d10-a9ee-460e-bb24-180882cccf83","apiCode":"Delete","hasPermission":true,"action":"productcategory3"}]}]}

**Comment by avyukta** [comment]
Fixed

**Comment by rvcssingh** [comment]
verified
